apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-update-consumer-api-deployment
  annotations:
    autor: Rodrigo Mahlow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-update-consumer-api
  template:
    metadata:
      labels:
        app: contact-update-consumer-api
    spec:
      containers:
      - name: contact-update-consumer-api
        image: maxcedro/contactsupdateconsumer:latest
        ports:
        - containerPort: 7070
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: contact-update-consumer-api-secrets
              key: DefaultConnection
        - name: SecretJWT
          valueFrom:
            secretKeyRef:
              name: contact-update-consumer-api-secrets
              key: SecretJWT
        - name: MassTransit__User
          valueFrom:
            secretKeyRef:
              name: contact-update-consumer-api-secrets
              key: User
        - name: MassTransit__Password
          valueFrom:
            secretKeyRef:
              name: contact-update-consumer-api-secrets
              key: Password
        - name: MassTransit__QueueName
          valueFrom:
            configMapKeyRef:
              name: contact-update-consumer-api-configmap
              key: QueueName
        - name: MassTransit__Server
          valueFrom:
            configMapKeyRef:
              name: contact-update-consumer-api-configmap
              key: Server
        - name: Integrations__ContactConsult__BasePath
          valueFrom:
            configMapKeyRef:
              name: contact-update-consumer-api-configmap
              key: BasePath
