apiVersion: v1
kind: Service
metadata:
  name: contact-update-consumer-api-nodeport
spec:
  selector:
    app: contact-update-consumer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
      nodePort: 30087
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: contact-update-consumer-api-lb
spec:
  selector:
    app: contact-update-consumer-api
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 7070
  type: LoadBalancer
